version: '3.8'

services:
  db:
    image: postgres:17-bullseye
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  django:
    image: liine_cooks_django
    ports:
      - 8000:8000
    command: 'python manage.py runserver 0.0.0.0:8000'
    # command: 'gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    volumes:
      - './liine_cooks:/app/:z'
    env_file:
      - .env
    environment:
      - RUNLEVEL=prod
    depends_on:
      - migrate

  migrate:
    build: ./liine_cooks
    image: liine_cooks_django
    command: python manage.py migrate
    volumes:
      - './liine_cooks:/app/:z'
    env_file:
      - .env
    environment:
      - RUNLEVEL=prod
    depends_on:
      - db
